In [1]:
import pandas as pd              # For loading and manipulating the CSV dataset
import numpy as np               # For numerical operations, e.g., creating mesh grid
from sklearn.model_selection import train_test_split  # For splitting data into training and test sets
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier # For implementing the AdaBoost algorithm
import lightgbm as lgb
from sklearn.tree import DecisionTreeClassifier       # For creating decision stumps (weak learners)
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix  # For evaluating model performance
from sklearn.preprocessing import StandardScaler , LabelEncoder

In [2]:
df = pd.read_csv(r"C:\Users\user\Music\Machine learning\SUPERVISED LEARNING\samples\SAMPLE DATASETS\Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.isna().sum() # FINDING NULL VALUE

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
Label = LabelEncoder() ## converting categorical text data into numberes
df["Geography"] = Label.fit_transform(df["Geography"])

In [6]:
Label = LabelEncoder()
df["Gender"] = Label.fit_transform(df["Gender"])

In [7]:
df.sample(10)

RowNumber  CustomerId     Surname  CreditScore  Geography  Gender  Age  \
409         410    15691625          Ko          537          1       0   41   
2439       2440    15586976    Alexeeva          566          0       0   42   
2724       2725    15812628        Dodd          453          1       0   38   
5944       5945    15715709        Shih          696          1       1   43   
8813       8814    15770375     Fanucci          850          1       0   26   
4418       4419    15644356  Prokhorova          682          2       0   47   
329         330    15624528          L?          664          1       1   26   
8593       8594    15722037     Alvarez          610          1       1   36   
3826       3827    15751774     Monnier          774          0       1   76   
7877       7878    15793070  Fiorentino          494          2       0   41   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
409        3  138306.34              1          1               0   
2439       6       0.00              1          1               0   
2724       8  120623.21              1          1               0   
5944       4  114091.38              1          0               1   
8813       8  123126.29              1          1               0   
4418      10  134032.01              1          1               0   
329        7  116244.14              2          1               1   
8593       7  115462.02              1          0               1   
3826       4  112510.89              1          1               1   
7877       2   69974.66              2          1               0   

      EstimatedSalary  Exited  
409         106761.47       0  
2439        180702.12       1  
2724        129697.99       0  
5944        159888.10       0  
8813         74425.41       0  
4418        144290.97       0  
329          95145.14       0  
8593         42581.04       0  
3826        143133.18       0  
7877        188426.13       1

In [8]:
# Selecting input(x) and output(y) columns
x = df[["CreditScore","Geography","Gender","Age","Tenure","Balance","NumOfProducts","HasCrCard","IsActiveMember","EstimatedSalary"]]
y = df["Exited"]  

In [9]:
x

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [10]:
X_train , X_test , y_train , y_test = train_test_split(x,y , test_size=0.2,random_state=42)
scaler = StandardScaler()

In [11]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ADA BOOST

In [12]:
weak_learner = DecisionTreeClassifier(max_depth=1) # using DecisionTreeClassifier
ada = AdaBoostClassifier(estimator=weak_learner, n_estimators=50, learning_rate=0.01, random_state=42) # using ada boost algrothim

In [13]:
ada.fit(X_train_scaled,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=0.01, random_state=42)

In [14]:
y_pred = ada.predict(X_test_scaled) # predicting on test value
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [16]:
accuracy_score(y_test,y_pred) # checking accuracy on test data

0.8035

In [17]:
print(classification_report(y_test,y_pred))  # classifcation report on test data

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1607
           1       0.00      0.00      0.00       393

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.45      2000
weighted avg       0.65      0.80      0.72      2000



C:\Users\user\anaconda.apk\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda.apk\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda.apk\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [18]:
confusion_matrix(y_test,y_pred)

array([[1607,    0],
       [ 393,    0]])

In [19]:
y_pred_t = ada.predict(X_train_scaled) # predicting of train data
y_pred_t

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [21]:
accuracy_score(y_train,y_pred_t) # accuracy of train data

0.7945

In [22]:
print(classification_report(y_train,y_pred_t))  # classifaction of train data

              precision    recall  f1-score   support

           0       0.79      1.00      0.89      6356
           1       0.00      0.00      0.00      1644

    accuracy                           0.79      8000
   macro avg       0.40      0.50      0.44      8000
weighted avg       0.63      0.79      0.70      8000



C:\Users\user\anaconda.apk\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda.apk\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\user\anaconda.apk\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# KNN

In [23]:
import pandas as pd

# Import train_test_split to split the data into training and test sets
from sklearn.model_selection import train_test_split

# Import KNeighborsClassifier to create and train the k-NN classification model
from sklearn.neighbors import KNeighborsClassifier

# Import metrics to evaluate the model's performance (accuracy, precision, recall, f1, confusion matrix, classification report)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Import StandardScaler to scale features (k-NN is sensitive to feature scales)
from sklearn.preprocessing import StandardScaler

In [24]:
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [25]:
x

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [26]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [27]:
X_train, X_test , y_train , y_test = train_test_split(x,y ,test_size=0.2,random_state=42)
model = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
# metric='euclidean' uses straight-line distance to find the closest points.

In [28]:
model.fit(X_train_scaled, y_train)

KNeighborsClassifier(metric='euclidean')

In [29]:
y_pred1 =model.predict(X_test_scaled)
y_pred1

array([0, 0, 0, ..., 1, 0, 0])

In [30]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [31]:
accuracy_score(y_test,y_pred1)

0.8355

In [32]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90      1607
           1       0.63      0.39      0.48       393

    accuracy                           0.84      2000
   macro avg       0.75      0.67      0.69      2000
weighted avg       0.82      0.84      0.82      2000



In [33]:
confusion_matrix(y_test,y_pred1)

array([[1519,   88],
       [ 241,  152]])

In [34]:
y_pred1_t =model.predict(X_train_scaled)
y_pred1_t

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [36]:
accuracy_score(y_train,y_pred1_t)

0.877875

In [37]:
print(classification_report(y_train,y_pred1_t))

              precision    recall  f1-score   support

           0       0.89      0.97      0.93      6356
           1       0.81      0.53      0.64      1644

    accuracy                           0.88      8000
   macro avg       0.85      0.75      0.78      8000
weighted avg       0.87      0.88      0.87      8000



In [38]:
confusion_matrix(y_train,y_pred1_t)

array([[6159,  197],
       [ 780,  864]])

# svc

In [39]:
import pandas as pd

# Import train_test_split to split the data into training and test sets
from sklearn.model_selection import train_test_split

# Import SVC to create and train the SVM classification model
from sklearn.svm import SVC

# Import metrics to evaluate the model's performance (accuracy, precision, recall, f1, confusion matrix, classification report)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [40]:
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [41]:
X_train , X_test ,y_train , y_test = train_test_split(x,y,test_size=0.2,random_state =42)
model2 = SVC(kernel='rbf', C=1.0, random_state=42, probability=True)
# kernel='rbf' allows non-linear boundaries
# C=1.0 balances margin maximization and misclassification penalty

In [42]:
model2.fit(X_train_scaled, y_train)

SVC(probability=True, random_state=42)

In [43]:
y_pred2 = model.predict(X_test_scaled)
y_pred2

array([0, 0, 0, ..., 1, 0, 0])

In [44]:
y_test

6252    0
4684    0
1731    0
4742    0
4521    0
       ..
6412    1
8285    0
7853    1
1095    1
6929    1
Name: Exited, Length: 2000, dtype: int64

In [45]:
accuracy_score(y_test,y_pred2)

0.8355

In [46]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90      1607
           1       0.63      0.39      0.48       393

    accuracy                           0.84      2000
   macro avg       0.75      0.67      0.69      2000
weighted avg       0.82      0.84      0.82      2000



In [47]:
confusion_matrix(y_test,y_pred2)

array([[1519,   88],
       [ 241,  152]])

In [48]:
y_pred2_t = model.predict(X_train_scaled)
y_pred2_t

array([0, 0, 0, ..., 0, 0, 0])

In [49]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [50]:
accuracy_score(y_train,y_pred2_t)

0.877875

In [51]:
print(classification_report(y_train,y_pred2_t))

              precision    recall  f1-score   support

           0       0.89      0.97      0.93      6356
           1       0.81      0.53      0.64      1644

    accuracy                           0.88      8000
   macro avg       0.85      0.75      0.78      8000
weighted avg       0.87      0.88      0.87      8000

